// Growth Report Data - May 11, 2026 to June 11, 2026
import { RawDeal, SalesPerformanceItem } from './types';

export const RAW_DEALS: RawDeal[] = [
    {
        id: 1,
        tenantName: "عباسية علي احمد عثمان",
        branch: "Mathwa 55",
        location: "Al Madinah",
        channel: "Other Portal (Bayut)",
        channelType: "Portal",
        isPaidSocial: false,
        monthlyRent: 7000,
        committedMonths: 12,
        committedGross: 84000,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 16800.0,
        salesRep: "Al-Shihana",
        contractStart: "16/5/2026",
        notes: ""
    },
    {
        id: 2,
        tenantName: "نوف أحمد علي آل عيسى",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "TikTok",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 4660,
        committedMonths: 1,
        committedGross: 4660,
        annualContract: false,
        mgmtFeePct: 25,
        mathwaaNet: 1165.0,
        salesRep: "Salsabila",
        contractStart: "1/6/2026",
        notes: "1-month, non-extendable"
    },
    {
        id: 3,
        tenantName: "إلهام أحمد سالم بنتن",
        branch: "Mathwa 13",
        location: "Al Arid",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 7100,
        committedMonths: 6,
        committedGross: 42600,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 8520.0,
        salesRep: "Amal",
        contractStart: "15/5/2026",
        notes: "6mo binding of annual; agreed 7100 vs 7600"
    },
    {
        id: 4,
        tenantName: "مريم فهد سلمان المغلوث",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "Social Media (generic)",
        channelType: "Paid Social - Unattributed",
        isPaidSocial: true,
        monthlyRent: 4480,
        committedMonths: 12,
        committedGross: 53760,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 13440.0,
        salesRep: "Raghad",
        contractStart: "1/6/2026",
        notes: "'social media' - platform not named"
    },
    {
        id: 5,
        tenantName: "Sebastian Kawka",
        branch: "Mathwa 33",
        location: "Al Olaya",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 6090,
        committedMonths: 3,
        committedGross: 18270,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 4567.5,
        salesRep: "Raghad / Al-Shihana",
        contractStart: "19/5/2026",
        notes: "3mo binding of annual"
    },
    {
        id: 6,
        tenantName: "Georges Khater",
        branch: "Mathwa 53",
        location: "Al Murooj",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 2750,
        committedMonths: 12,
        committedGross: 33000,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 6600.0,
        salesRep: "Amal",
        contractStart: "1/6/2026",
        notes: ""
    },
    {
        id: 7,
        tenantName: "نهى ناصر علي الجهني",
        branch: "Mathwa 20",
        location: "Al Zahraa",
        channel: "Meta (Instagram)",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 2700,
        committedMonths: 6,
        committedGross: 16200,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 3240.0,
        salesRep: "Amal",
        contractStart: "7/5/2026",
        notes: "Instagram ad; existing-tenant room transfer 100->101, attributed per instruction"
    },
    {
        id: 8,
        tenantName: "عبدالمحسن التركي",
        branch: "Mathwa 55",
        location: "Al Madinah",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: null,
        committedMonths: 0.2,
        committedGross: 1620,
        annualContract: false,
        mgmtFeePct: 20,
        mathwaaNet: 324.0,
        salesRep: "Amal",
        contractStart: "21/5/2026",
        notes: "Short stay: 270 SAR/night x 6 nights"
    },
    {
        id: 9,
        tenantName: "روان فرج رده الرحيلي",
        branch: "Mathwa 17",
        location: "Al Yasmin",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 4500,
        committedMonths: 3,
        committedGross: 13500,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 4050.0,
        salesRep: "Al-Shihana",
        contractStart: "20/6/2026",
        notes: "3mo binding of annual"
    },
    {
        id: 10,
        tenantName: "احمد عبدالعزيز البراهيم",
        branch: "Mathwa 55",
        location: "Al Madinah",
        channel: "Other Portal (Airbnb)",
        channelType: "Portal",
        isPaidSocial: false,
        monthlyRent: null,
        committedMonths: 0.1,
        committedGross: 405,
        annualContract: false,
        mgmtFeePct: 20,
        mathwaaNet: 81.0,
        salesRep: "Amal",
        contractStart: "20/5/2026",
        notes: "Short stay: 135 SAR/night x 3 nights"
    },
    {
        id: 11,
        tenantName: "سالي فهر عفره",
        branch: "Mathwa 33",
        location: "Al Olaya",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 5600,
        committedMonths: 1,
        committedGross: 5600,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 1400.0,
        salesRep: "Amal",
        contractStart: "28/5/2026",
        notes: "Stated 1mo; dates span ~2mo. Conservative=1"
    },
    {
        id: 13,
        tenantName: "روان صالح ابراهيم النعيم",
        branch: "Mathwa 5",
        location: "Al Arid",
        channel: "Social Media (generic)",
        channelType: "Paid Social - Unattributed",
        isPaidSocial: true,
        monthlyRent: 3400,
        committedMonths: 1,
        committedGross: 3400,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 680.0,
        salesRep: "Al-Shihana",
        contractStart: "1/6/2026",
        notes: "'social media' - platform not named"
    },
    {
        id: 14,
        tenantName: "سمر مناحي زامل الشهراني",
        branch: "Mathwa 51",
        location: "Al Narjis",
        channel: "Existing Tenant",
        channelType: "Existing/Other",
        isPaidSocial: false,
        monthlyRent: 3650,
        committedMonths: 2,
        committedGross: 7300,
        annualContract: true,
        mgmtFeePct: 10,
        mathwaaNet: 730.0,
        salesRep: "Amal",
        contractStart: "6/6/2026",
        notes: "Already a resident"
    },
    {
        id: 15,
        tenantName: "رجاء صالح احمد القرني",
        branch: "Mathwa 5",
        location: "Al Arid",
        channel: "TikTok",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 3300,
        committedMonths: 12,
        committedGross: 39600,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 7920.0,
        salesRep: "Amal",
        contractStart: "13/6/2026",
        notes: ""
    },
    {
        id: 16,
        tenantName: "محمد عبدالرحمن العويس",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "Meta (Instagram)",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 4000,
        committedMonths: 1,
        committedGross: 4000,
        annualContract: false,
        mgmtFeePct: 25,
        mathwaaNet: 1000.0,
        salesRep: "Al-Shihana",
        contractStart: "1/6/2026",
        notes: "Instagram ads; 1mo+1day non-extendable"
    },
    {
        id: 17,
        tenantName: "جمانة عبدالرحمن المدهون",
        branch: "Mathwa 15",
        location: "Al Yasmin",
        channel: "Unknown",
        channelType: "Unknown",
        isPaidSocial: false,
        monthlyRent: 3500,
        committedMonths: 2,
        committedGross: 7000,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 2100.0,
        salesRep: "Amal",
        contractStart: "31/5/2026",
        notes: "Source blank; stated 2mo binding (dates span 3mo)"
    },
    {
        id: 18,
        tenantName: "محمد روش صياح العنزي",
        branch: "Mathwa 43",
        location: "Al Ta'awun",
        channel: "Walk-in",
        channelType: "Existing/Other",
        isPaidSocial: false,
        monthlyRent: 9000,
        committedMonths: 12,
        committedGross: 108000,
        annualContract: true,
        mgmtFeePct: 7,
        mathwaaNet: 7560.0,
        salesRep: "Raghad",
        contractStart: "31/5/2026",
        notes: "Saw the building (Al-Ta'awun); agreed 9000 vs 9558"
    },
    {
        id: 19,
        tenantName: "امل هايل فرحان العنزي",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "TikTok",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 5444,
        committedMonths: 1.25,
        committedGross: 6805,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 1701.25,
        salesRep: "Amal",
        contractStart: "19/6/2026",
        notes: "Month + 1 week"
    },
    {
        id: 20,
        tenantName: "ناصر عبدالرحمن الملحم",
        branch: "Mathwa 43",
        location: "Al Ta'awun",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 10752,
        committedMonths: 2,
        committedGross: 21504,
        annualContract: true,
        mgmtFeePct: 7,
        mathwaaNet: 1505.28,
        salesRep: "Amal",
        contractStart: "4/6/2026",
        notes: "2mo binding of annual"
    },
    {
        id: 21,
        tenantName: "فتون محمد العتيبي",
        branch: "Mathwa 31",
        location: "Al Salam",
        channel: "Existing Tenant",
        channelType: "Existing/Other",
        isPaidSocial: false,
        monthlyRent: 2970,
        committedMonths: 12,
        committedGross: 35640,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 10692.0,
        salesRep: "Amal",
        contractStart: "3/6/2026",
        notes: "Already a resident"
    },
    {
        id: 22,
        tenantName: "نعمة يحي عبدالله بشر",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "Existing Tenant",
        channelType: "Existing/Other",
        isPaidSocial: false,
        monthlyRent: 4000,
        committedMonths: 1,
        committedGross: 4000,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 1000.0,
        salesRep: "Al-Shihana",
        contractStart: "1/6/2026",
        notes: "Already a resident"
    },
    {
        id: 23,
        tenantName: "Gayatri Neti",
        branch: "Mathwa 33",
        location: "Al Olaya",
        channel: "Unknown",
        channelType: "Unknown",
        isPaidSocial: false,
        monthlyRent: 5600,
        committedMonths: 12,
        committedGross: 67200,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 16800.0,
        salesRep: "Al-Shihana",
        contractStart: "6/6/2026",
        notes: "Lead source blank"
    },
    {
        id: 24,
        tenantName: "ضي توفيق فهد الجميل",
        branch: "Mathwa 23",
        location: "Al Yarmouk",
        channel: "Social Media (generic)",
        channelType: "Paid Social - Unattributed",
        isPaidSocial: true,
        monthlyRent: 4500,
        committedMonths: 3,
        committedGross: 13500,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 4050.0,
        salesRep: "Amal",
        contractStart: "25/6/2026",
        notes: "'social media' - platform not named"
    },
    {
        id: 25,
        tenantName: "احمد فراج على فراج",
        branch: "Mathwa 33",
        location: "Al Olaya",
        channel: "Other Portal (Bayut)",
        channelType: "Portal",
        isPaidSocial: false,
        monthlyRent: 6500,
        committedMonths: 12,
        committedGross: 78000,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 19500.0,
        salesRep: "Al-Shihana",
        contractStart: "9/6/2026",
        notes: ""
    },
    {
        id: 26,
        tenantName: "أميمه عابدين محمد",
        branch: "Mathwa 20",
        location: "Al Zahraa",
        channel: "Meta (Facebook)",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 2500,
        committedMonths: 2,
        committedGross: 5000,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 1000.0,
        salesRep: "Amal",
        contractStart: "12/6/2026",
        notes: "Facebook ad named explicitly"
    },
    {
        id: 27,
        tenantName: "فيء عبيد سعيد العيافي",
        branch: "Mathwa 32",
        location: "Al Qayrawan",
        channel: "TikTok",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 4500,
        committedMonths: 6,
        committedGross: 27000,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 6750.0,
        salesRep: "Amal",
        contractStart: "9/6/2026",
        notes: "6mo binding of annual"
    },
    {
        id: 28,
        tenantName: "هبة احمد إبراهيم هوساوي",
        branch: "Mathwa 20",
        location: "Al Zahraa",
        channel: "Meta (Instagram)",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 2400,
        committedMonths: 1,
        committedGross: 2400,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 480.0,
        salesRep: "Al-Shihana",
        contractStart: "16/6/2026",
        notes: ""
    },
    {
        id: 29,
        tenantName: "شعاع سعود ال مغيره",
        branch: "Mathwa 38",
        location: "Al Sulaimaniyah",
        channel: "Social Media (generic)",
        channelType: "Paid Social - Unattributed",
        isPaidSocial: true,
        monthlyRent: 4790,
        committedMonths: 1,
        committedGross: 4790,
        annualContract: true,
        mgmtFeePct: 25,
        mathwaaNet: 1197.5,
        salesRep: "Amal",
        contractStart: "12/6/2026",
        notes: "'social media sites'; 4290+500 (two in studio)"
    },
    {
        id: 30,
        tenantName: "فاطمه علي أحمد المحسن",
        branch: "Mathwa 42",
        location: "Al Arid",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 1700,
        committedMonths: 2,
        committedGross: 3400,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 1020.0,
        salesRep: "Al-Shihana",
        contractStart: "27/6/2026",
        notes: "Shared room. Dedup: kept unit 140, dropped 184 repeat"
    },
    {
        id: 31,
        tenantName: "نور علي حسن العلوان",
        branch: "Mathwa 42",
        location: "Al Arid",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 1700,
        committedMonths: 2,
        committedGross: 3400,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 1020.0,
        salesRep: "Al-Shihana",
        contractStart: "27/6/2026",
        notes: "Shared room. Dedup: kept unit 140, dropped 184 repeat"
    },
    {
        id: 34,
        tenantName: "عذاري علي راشد القلهاتي",
        branch: "Mathwa 37",
        location: "Al Arid",
        channel: "TikTok",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 2600,
        committedMonths: 1,
        committedGross: 2600,
        annualContract: true,
        mgmtFeePct: 30,
        mathwaaNet: 780.0,
        salesRep: "Al-Shihana",
        contractStart: "19/6/2026",
        notes: "'social media / TikTok' - TikTok named"
    },
    {
        id: 35,
        tenantName: "زهراء علي حسن البصري",
        branch: "Mathwa 7",
        location: "Al Arid",
        channel: "Meta (Instagram)",
        channelType: "Paid Social - Attributed",
        isPaidSocial: true,
        monthlyRent: 2900,
        committedMonths: 2,
        committedGross: 5800,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 1160.0,
        salesRep: "Al-Shihana",
        contractStart: "12/6/2026",
        notes: "Instagram"
    },
    {
        id: 36,
        tenantName: "مؤيد بدر زين السيد",
        branch: "Mathwa 51",
        location: "Al Narjis",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 6500,
        committedMonths: 1,
        committedGross: 6500,
        annualContract: true,
        mgmtFeePct: 10,
        mathwaaNet: 650.0,
        salesRep: "Al-Shihana",
        contractStart: "17/7/2026",
        notes: ""
    },
    {
        id: 37,
        tenantName: "Remaa Adil",
        branch: "Mathwa 56",
        location: "Al Madinah",
        channel: "Organic Search",
        channelType: "Organic/Other",
        isPaidSocial: false,
        monthlyRent: 8050,
        committedMonths: 1,
        committedGross: 8050,
        annualContract: false,
        mgmtFeePct: 20,
        mathwaaNet: 1610.0,
        salesRep: "Amal",
        contractStart: "28/6/2026",
        notes: "'Search on internet' - non-paid"
    },
    {
        id: 38,
        tenantName: "محمد محسن محمد عبد المنعم",
        branch: "Mathwa 33",
        location: "Al Olaya",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 5400,
        committedMonths: 3,
        committedGross: 16200,
        annualContract: false,
        mgmtFeePct: 25,
        mathwaaNet: 4050.0,
        salesRep: "Fahmida",
        contractStart: "17/6/2026",
        notes: "3mo binding contract"
    },
    {
        id: 39,
        tenantName: "خالد علي حميد الحنيطي",
        branch: "Mathwa 13",
        location: "Al Arid",
        channel: "Referral",
        channelType: "Referral",
        isPaidSocial: false,
        monthlyRent: 5600,
        committedMonths: 7,
        committedGross: 39200,
        annualContract: true,
        mgmtFeePct: 20,
        mathwaaNet: 7840.0,
        salesRep: "Al-Shihana",
        contractStart: "1/7/2026",
        notes: "Annual, 7mo binding"
    }
];

export const REPORT_DATA = {
    period: {
        en: "May 11, 2026 to June 11, 2026",
        ar: "١١ مايو ٢٠٢٦ إلى ١١ يونيو ٢٠٢٦"
    },
    financials: {
        netCashCollected: 167461.00, // Total first-month values collected
        mathwaaRevenue: 34049.64,    // Mathwaa's monthly share total
        mathwaaLTV: 162983.53,       // Mathwaa's lifetime value share across full contract terms
        totalLTV: 793904.00,         // Grand total property gross contract value
        
        // Cumulative Property Revenue by Channel Groups
        digitalAdsTotal: 189515.00,     // TikTok (80665) + Meta (33400) + Generics (75450)
        listingPlatformsTotal: 162405.00, // Portal (Bayut/Airbnb)
        referralOtherTotal: 441984.00,   // Referral (204794) + Organic (8050) + Existing (46940) + Walk-in (108000) + Unknown (74200)

        // Mathwaa Direct Share split by Channel Groups
        digitalAdsShare: 44563.75,       // TikTok (18316.25) + Meta (6880) + Generics (19367.5)
        listingPlatformsShare: 36381.00,  // Portal (36381)
        referralOtherShare: 82038.78,    // Referral (41546.78) + Organic (1610) + Existing (12422) + Walk-in (7560) + Unknown (18900)

        // Ad spend fields
        adSpendTikTok: 4702.00,
        adSpendMeta: 2746.00,
        adSpendSnapchat: 0.00,
        
        get adSpend() {
            return this.adSpendTikTok + this.adSpendMeta;
        },
        
        get marketingSpend() {
            return this.adSpend + 1500; // Media spend + Creative Production (1500)
        },
        
        get roi() {
            // Media ROAS = Property Value from Paid Channels divided by Media Spend
            // Total digital ads total including generics is 189515. Ad spend is 6184.
            return Number((this.digitalAdsTotal / this.adSpend).toFixed(2));
        },

        get mathwaaRoi() {
            return Number((this.digitalAdsShare / this.adSpend).toFixed(2));
        }
    },
    salesTeam: [
        { name: "Amal", januaryValue: 15177.14, lifetimeValue: 159960.68 },
        { name: "Al-Shihana", januaryValue: 13846.25, lifetimeValue: 155155.00 },
        { name: "Raghad", januaryValue: 2511.25, lifetimeValue: 30135.00 },
        { name: "Fahmida", januaryValue: 1350.00, lifetimeValue: 4050.00 },
        { name: "Salsabila", januaryValue: 1165.00, lifetimeValue: 1165.00 }
    ] as SalesPerformanceItem[],
    spendBreakdown: [
        { name_en: 'TikTok Ads', name_ar: 'إعلانات تيك توك', value: 4702, color: '#000000' },
        { name_en: 'Meta Ads', name_ar: 'إعلانات ميتا', value: 2746, color: '#1877F2' },
        { name_en: 'Creative Production', name_ar: 'الإنتاج الإبداعي', value: 1500, color: '#A855F7' }
    ],
    sourcePerformance: [
        { name_en: 'TikTok', name_ar: 'تيك توك', total: 80665, share: 18316.25 },
        { name_en: 'Meta (Insta+FB)', name_ar: 'ميتا (إنستغرام/فيسبوك)', total: 33400, share: 6880 },
        { name_en: 'Social Media (generic)', name_ar: 'تواصل اجتماعي (عام)', total: 75450, share: 19367.5 },
        { name_en: 'Referral', name_ar: 'قناة الإحالة Direct', total: 204794, share: 41546.78 },
        { name_en: 'Portal (Bayut/Airbnb)', name_ar: 'بوابات العقارات', total: 162405, share: 36381 },
        { name_en: 'Organic Search', name_ar: 'محركات البحث', total: 8050, share: 1610 },
        { name_en: 'Existing Tenant', name_ar: 'تمديد عقود نزلاء', total: 46940, share: 12422 },
        { name_en: 'Walk-in', name_ar: 'زيارات مباشرة للمبنى', total: 108000, share: 7560 },
        { name_en: 'Unknown', name_ar: 'مصادر غير مسجلة', total: 74200, share: 18900 }
    ],
    branchPerformance: [
        { name_en: 'Mathwa 33 (Olaya)', name_ar: 'العليا ٣٣', total: 185270, share: 46317.5, count: 5 },
        { name_en: 'Mathwa 43 (Ta\'awun)', name_ar: 'التعاون ٤٣', total: 129504, share: 9065.28, count: 2 },
        { name_en: 'Mathwa 55 (Madinah)', name_ar: 'المدينة ٥٥', total: 86025, share: 17205, count: 3 },
        { name_en: 'Mathwa 13 (Al Arid)', name_ar: 'العارض ١٣', total: 81800, share: 16360, count: 2 },
        { name_en: 'Mathwa 38 (Sulaimaniyah)', name_ar: 'السليمانية ٣٨', total: 78015, share: 19503.75, count: 6 },
        { name_en: 'Mathwa 5 (Al Arid)', name_ar: 'العارض ٥', total: 43000, share: 8600, count: 2 },
        { name_en: 'Mathwa 31 (Al Salam)', name_ar: 'السلام ٣١', total: 35640, share: 10692, count: 1 },
        { name_en: 'Mathwa 53 (Al Murooj)', name_ar: 'المروج ٥٣', total: 33000, share: 6600, count: 1 },
        { name_en: 'Mathwa 32 (Qayrawan)', name_ar: 'القيروان ٣٢', total: 27000, share: 6750, count: 1 },
        { name_en: 'Mathwa 20 (Al Zahraa)', name_ar: 'الزهراء ٢٠', total: 23600, share: 4720, count: 3 },
        { name_en: 'Mathwa 51 (Al Narjis)', name_ar: 'النرجس ٥١', total: 13800, share: 1380, count: 2 },
        { name_en: 'Mathwa 17 (Al Yasmin)', name_ar: 'الياسمين ١٧', total: 13500, share: 4050, count: 1 },
        { name_en: 'Mathwa 23 (Al Yarmouk)', name_ar: 'اليرموك ٢٣', total: 13500, share: 4050, count: 1 },
        { name_en: 'Mathwa 56 (Madinah)', name_ar: 'المدينة ٥٦', total: 8050, share: 1610, count: 1 },
        { name_en: 'Mathwa 15 (Al Yasmin)', name_ar: 'الياسمين ١٥', total: 7000, share: 2100, count: 1 },
        { name_en: 'Mathwa 42 (Al Arid)', name_ar: 'العارض ٤٢', total: 6800, share: 2040, count: 2 },
        { name_en: 'Mathwa 7 (Al Arid)', name_ar: 'العارض ٧', total: 5800, share: 1160, count: 1 },
        { name_en: 'Mathwa 37 (Al Arid)', name_ar: 'العارض ٣٧', total: 2600, share: 780, count: 1 }
    ]
};
