
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CloseIcon } from './Icons';

interface FormulaModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: 'en' | 'ar';
}

const definitions = {
  en: [
    {
      label: "Mathwaa Revenue",
      formula: "Σ (Tenant Monthly Rent × Mathwaa % Share)",
      description: "The specific portion of revenue recognized for Mathwaa for the reporting period (May 11 - June 11, 2026). Share percentages vary by unit type (e.g., 20%, 25%, 30%)."
    },
    {
      label: "Mathwaa LTV (Lifetime Value)",
      formula: "Σ (Contract Value × Mathwaa % Share)",
      description: "The projected total revenue Mathwaa will earn over the full duration of the signed leases during this reporting period (e.g., 12 months)."
    },
    {
      label: "Total Revenue Marketing ROI",
      formula: "Total Gross Property Revenue from Paid Campaigns / Media Spend",
      description: "Return on Investment calculated using the total gross property lease value generated by tenants acquired through paid digital channels divided by the direct media cost. It shows gross lease creation power (e.g., 30.65×)."
    },
    {
      label: "Mathwaa Share Marketing ROI",
      formula: "Mathwaa Net Share from Paid Campaigns / Media Spend",
      description: "Return on Investment calculated using only Mathwaa's actual percentage-based management share from paid campaigns divided by the media cost (e.g., 7.21×)."
    },
    {
      label: "Attributed Revenue",
      formula: "Σ (Mathwaa Revenue for Tenants where Source ∈ {Paid Ads})",
      description: "Revenue specifically generated from tenants acquired through TikTok, Facebook, and Instagram paid campaigns."
    }
  ],
  ar: [
    {
      label: "إيرادات مثوى",
      formula: "مجموع (إيجار المستأجر × نسبة حصة مثوى)",
      description: "الجزء المحدد من الإيرادات المستحق لشركة مثوى لفترة التقرير (١١ مايو - ١١ يونيو ٢٠٢٦). تختلف النسب حسب الوحدة (مثلاً ٢٠٪، ٢٥٪، ٣٠٪)."
    },
    {
      label: "القيمة الدائمة لمثوى (LTV)",
      formula: "مجموع (قيمة العقد × نسبة حصة مثوى)",
      description: "إجمالي الإيرادات المتوقعة التي ستكسبها مثوى على مدار مدة العقود الموقعة بالكامل خلال فترة التقرير (مثلاً ١٢ شهراً)."
    },
    {
      label: "عائد الاستثمار التسويقي (إجمالي الإيرادات)",
      formula: "إجمالي إيرادات العقارات المنسوبة للحملات المدفوعة / الإنفاق الإعلامي",
      description: "عائد الاستثمار المحسوب باستخدام القيمة الإجمالية لعقود الإيجار الناتجة عن الحملات الإعلانية المدفوعة مقسومة على تكلفة الإعلام المباشرة، مما يوضح القوة الإجمالية للمبيعات (مثال: ٣٠.٦٥ ضعفاً)."
    },
    {
      label: "عائد الاستثمار التسويقي (حصة مثوى فقط)",
      formula: "حصة مثوى الصافية من الحملات المدفوعة / الإنفاق الإعلامي",
      description: "عائد الاستثمار المحسوب بناءً فقط على حصة إدارة شركة مثوى الفعلية (النسبة المئوية للاستحقاق) الناتجة من الحملات المدفوعة مقسومة على تكلفة الإعلام (مثال: ٧.٢١ ضعفاً)."
    },
    {
       label: "الإيرادات المنسوبة",
       formula: "مجموع (إيرادات مثوى للمستأجرين حيث المصدر ∈ {إعلانات مدفوعة})",
       description: "الإيرادات الناتجة تحديداً عن المستأجرين الذين تم استقطابهم عبر حملات تيك توك وفيسبوك وانستغرام المدفوعة."
    }
  ]
};

const FormulaModal: React.FC<FormulaModalProps> = ({ isOpen, onClose, lang }) => {
  const content = definitions[lang];
  const isRTL = lang === 'ar';

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
        <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onClick={onClose}
        />
        <motion.div 
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className={`relative bg-white w-full max-w-2xl rounded-3xl shadow-2xl overflow-hidden border border-gray-100 flex flex-col max-h-[90vh] ${isRTL ? 'text-right' : 'text-left'}`}
            dir={isRTL ? 'rtl' : 'ltr'}
        >
             <div className="bg-gray-50/50 border-b border-gray-100 p-6 flex justify-between items-center">
                 <div>
                    <h3 className="text-2xl font-bold text-[#4A2C5A]">
                        {lang === 'en' ? 'Calculations & Formulas' : 'طرق الاحتساب والمعادلات'}
                    </h3>
                 </div>
                 <button 
                    onClick={onClose}
                    className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-500 transition-colors"
                 >
                    <CloseIcon className="w-5 h-5" />
                 </button>
             </div>

             <div className="p-6 overflow-y-auto space-y-6">
                {content.map((item, idx) => (
                    <div key={idx} className="bg-gray-50 rounded-2xl p-5 border border-gray-100">
                        <h4 className="text-[#1D1D1F] font-bold text-lg mb-2">{item.label}</h4>
                        <div className="bg-white rounded-lg p-3 border border-gray-200 mb-3 font-mono text-xs sm:text-sm text-[#4A2C5A] overflow-x-auto">
                            {item.formula}
                        </div>
                        <p className="text-gray-500 text-sm leading-relaxed">
                            {item.description}
                        </p>
                    </div>
                ))}
             </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default FormulaModal;
